// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNDQx_AHiev6rvIjFA2W2kOK76WolTBD0',
    appId: '1:965270955948:web:3713e1b17e66da9027fc09',
    messagingSenderId: '965270955948',
    projectId: 'my-guardian-sense',
    authDomain: 'my-guardian-sense.firebaseapp.com',
    storageBucket: 'my-guardian-sense.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrmeZ4WwMoDBjy-m0G_s_IklEIjEWLhks',
    appId: '1:965270955948:android:2f1539a97cfff86427fc09',
    messagingSenderId: '965270955948',
    projectId: 'my-guardian-sense',
    storageBucket: 'my-guardian-sense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa3oUsLjBao1RCOQ_Lh9rAXkSjCkbZQq8',
    appId: '1:965270955948:ios:f40f272d4c1bfd8027fc09',
    messagingSenderId: '965270955948',
    projectId: 'my-guardian-sense',
    storageBucket: 'my-guardian-sense.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa3oUsLjBao1RCOQ_Lh9rAXkSjCkbZQq8',
    appId: '1:965270955948:ios:f40f272d4c1bfd8027fc09',
    messagingSenderId: '965270955948',
    projectId: 'my-guardian-sense',
    storageBucket: 'my-guardian-sense.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNDQx_AHiev6rvIjFA2W2kOK76WolTBD0',
    appId: '1:965270955948:web:d0f79655558e4adf27fc09',
    messagingSenderId: '965270955948',
    projectId: 'my-guardian-sense',
    authDomain: 'my-guardian-sense.firebaseapp.com',
    storageBucket: 'my-guardian-sense.firebasestorage.app',
  );
}
